### ISSUE TITLE
Run time error in project

### ISSUE THREAD

**Issue by kholoudAlSaleh** [FranciscoAriza/cloudsse#1]
* When building the project using "mvn clean compile assembly:single" I get the following warnings:

[WARNING] Some problems were encountered while building the effective model for org.crypto.sse:SSELab:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.pdfbox:pdfbox:jar -> version 2.0.2 vs 1.8.10 @ line 117, column 17
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.poi:poi:jar -> version 3.14 vs 3.15-beta1 @ line 127, column 17
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 12, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 

* After running the project using " java -jar SSELab-1.0-SNAPSHOT-jar-with-dependencies.jar"a nd entering the path the contains the documents to index I get a runtime error:
Caused by: java.util.jar.JarException: file:/home/khsaad/Downloads/cloudsse-master/target/SSELab-1.0-SNAPSHOT-jar-with-dependencies.jar has unsigned entries - org/bouncycastle/LICENSE.class
	at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:459)
	at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
	at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
	at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
	at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:192)
	at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:220)
	at java.base/javax.crypto.Cipher.getInstance(Cipher.java:718)

Can you please help me with this I have been trying to solve the problem for more than a week now but with no luck.

Thanks in advance

**Comment by phamtrantiendat** [comment]
@FranciscoAriza i have the same problem. please help us
